name: 'Sendgrid template version update'
description: 'Sendgrid template version update'
inputs:
  api-key:
    description: 'sendgrid api key for authorization'
    required: true
  id-content-map:
    description: 'template-id-version-id and html content map'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'